name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  init_db:
    runs-on: self-hosted
    steps:
      - name: Run db
        run: echo "DB started"
      - name: Remove db
        run: |
            docker stop books-db
            docker rm books-db
            echo "DB removed"
      - name: Run
        run: docker run --name books-db -p 27017:27017 -e MONGO_INITDB_DATABASE=${{ secrets.DB_NAME }} -d mongo:latest
      - name: Init DB
        run: |
            docker ps
            echo "DB initialized"
  build:
    runs-on: self-hosted
    needs: init_db
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy image to docker hub
        run: |
            echo "Initial setup"
            cat ~/credentials.txt | docker login --username kevin117rodriguez --password-stdin
            docker build -t kevin117rodriguez/appimage .
            docker tag kevin117rodriguez/appimage kevin117rodriguez/appimage
            docker push kevin117rodriguez/appimage
  test:
    runs-on: self-hosted
    needs: [init_db, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: echo "Tests passed"
  deploy:
    runs-on: self-hosted
    needs: [build, test, init_db]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy
        run: |
            echo "Deploying"
            docker pull kevin117rodriguez/appimage
            docker run --name app-deploy -e PORT=3000 -e DB_HOST=${{secrets.DB_HOST}} -e DB_PORT=${{secrets.DB_PORT}} -e DB_NAME=${{secrets.DB_NAME}} -p 3000:3000 kevin117rodriguez/appimage
            docker ps
            echo "Deployed"
