name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  init_db:
    runs-on: self-hosted
    steps:
      - name: Run db
        run: echo "DB started"
      - name: Run
        run: docker run --name some-mongo -p 27017:27017 -e MONGO_INITDB_DATABASE=${{ secrets.DB_NAME }} -d mongo:latest
      - name: Init DB
        run: |
            docker ps
            echo "DB initialized"
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: initial setup
        run: echo "Initial setup"
      - name: Init Build
        run: echo "Build started"
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: echo "Tests passed"
  deploy:
    runs-on: self-hosted
    needs: [build, test, init_db]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy
        run: echo "Deployed successfully"
