name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  init_db:
    runs-on: self-hosted
    steps:
      - name: Run db
        run: echo "DB started"
      - name: Run
        run: docker run --name books-db -p 27017:27017 -e MONGO_INITDB_DATABASE=${{ secrets.DB_NAME }} -d mongo:latest
      - name: Init DB
        run: |
            docker ps
            echo "DB initialized"
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to docker
        run: |
            echo "Logging in to docker"
            docker login -u ${{ secrets.CI_REGISTRY_USER }} -p ${{ secrets.CI_REGISTRY_PASSWORD }}
            echo "Logged in to docker"
      - name: Deply image to docker
        run: |
            echo "Initial setup"
            whoami
            docker build -t ${{secrets.IMAGE_TAG}} .
            docker tag ${{secrets.IMAGE_TAG}} ${{secrets.IMAGE_TAG}}
            docker push ${{secrets.IMAGE_TAG}}
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: echo "Tests passed"
  deploy:
    runs-on: self-hosted
    needs: [build, test, init_db]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy
        run: |
            echo "Deploying"
            docker pull $IMAGE_TAG
            docker run --name app-deploy -e PORT=3000 -e DB_HOST=${{secrets.DB_HOST}} -e DB_PORT=${{secrets.DB_PORT}} -e DB_NAME=${{secrets.DB_NAME}} -p 3000:3000 ${{secrets.IMAGE_TAG}}
            docker ps
            echo "Deployed"
